### ISSUE TITLE
Placeholder doesn't work

### ISSUE THREAD

**Issue by JasonWu55** [KyleNanakdewa/SimpleWebhooks#10]
config.yml
```
  other:

    # An example that can be used through a command block, useful if you want to fire webhooks using redstone.
    # Or, set up an alias command, and your admins can trigger webhooks with commands.
    # Command is "/webhooks execute example-command-block [param 1] [param 2] [param 3]"
    # You can have any number of params in the command.
    web:
      url: http://192.168.1.126:9000/hooks/web
      json:
        code: "{PLAYER_UUID}"
```

The webhook server result
```
[webhook] 2022/07/30 10:52:05 [f21062] incoming HTTP POST request from 172.18.0.3:50752
[webhook] 2022/07/30 10:52:05 [f21062] web got matched
[webhook] 2022/07/30 10:52:05 [f21062] web hook triggered successfully
[webhook] 2022/07/30 10:52:05 [f21062] 200 | 0 B | 132.487µs | 192.168.1.126:9000 | POST /hooks/web
[webhook] 2022/07/30 10:52:05 [f21062] executing /root/webhook/gen.sh (/root/webhook/gen.sh) with arguments ["/root/webhook/gen.sh" "{PLAYER_UUID}"] and environment [] using /root/webhook as cwd
[webhook] 2022/07/30 10:52:05 [f21062] command output:
[webhook] 2022/07/30 10:52:05 [f21062] finished handling web
```
