### ISSUE TITLE
Command block arguments - Select all arguments

### ISSUE THREAD

**Issue by YJJcoolcool** [KyleNanakdewa/SimpleWebhooks#6]
How do I select the whole argument string?
For example, when I execute the command `/webhooks execute senddiscordmessage Hello how are you?`, I want the whole string "Hello how are you?" to be sent.
This is my current config:

```
other:
    senddiscordmessage:
      url: ...
      json:
        content: "{COMMAND_PARAM_1}"
```
