### ISSUE TITLE
Embedding in Discord

### ISSUE THREAD

**Issue by Bergene** [KyleNanakdewa/SimpleWebhooks#9]
Hi.

I have been trying to use the 'embed' feature in Discord with your plugin. I can't seem to make it work. 

I don't know Java nor YAML but this is what I've tried: 

```
json:
        content: '{COMMAND_PARAM_1}'
        embeds:
        - title: 'asdf'
          description: 'asdfasdf'
          color: 2752256
```

```
json:
        content: '{COMMAND_PARAM_1}'
        embeds:
                - title: 'asdf'
                - description: 'asdfasdf'
                - color: '2752256'
```

Is this possible, am I doing it wrong?
